Repository boostcampwm-2024/web09-DailyRoad, pull requests merged in 2024-12, with the labels that each got.

#223 리드미에 기술 스택 뱃지 추가
  README.md
Labels: 📖 문서

#237 내 지도,코스 조회 페이지네이션 파라미터 적용
  backend/src/course/CourseController.ts
  backend/src/course/CourseService.ts
  backend/src/map/MapController.ts
  backend/src/map/MapRepository.ts
  backend/src/map/MapService.ts
Labels: BE, 🚨 긴급

#242 지도/코스 기본 썸네일 변경
  backend/src/common/consts/index.ts
  backend/src/course/entity/Course.ts
  backend/src/map/entity/Map.ts
Labels: BE, ⚙️ 리팩터링

#243 지도 수정 시 thumbnail 이 들어가지 않는 문제 해결
  backend/src/map/MapService.ts
Labels: BE, 🚑 버그, 🚨 긴급

#240 배너 슬라이더 드래그시 창 이동하지 않도록 수정
  frontend/src/components/Banner/BannerSlider.tsx
Labels: FE, 🌈 기능 개선
