Repository boostcampwm-2024/web09-DailyRoad, pull requests merged in 2024-11, with the labels that each got.

#7 CI 파이프라인 : 린트 확인
  .github/CI_PIPELINE.yml
Labels: 🛠️ 설정

#5 초기 환경을 세팅한다
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/config/TypeOrmConfigService.ts
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.build.json
  backend/tsconfig.json
  backend/yarn.lock
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/.prettierrc
  frontend/index.html
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: 🛠️ 설정

#46 Globalpipe를 지워버린 것을 복구
  backend/src/main.ts
Labels: BE, 👻 사소한 수정

#99 CORS 문제 해결
  backend/resources/nginx.conf
  backend/src/main.ts
Labels: BE, 🚑 버그, 🛠️ 설정, 🙏 배포

#75 프로젝트 리드미 작성
  README.md
Labels: 📖 문서

#121 핫픽스 throttler 설정 변경
  backend/src/app.module.ts
Labels: BE, 🚨 긴급

#129 map 기능 레포지토리 테스트 작성
  backend/test/map/fixture/map.fixture.ts
  backend/test/map/fixture/map.fixture.type.ts
  backend/test/map/map.repository.test.ts
Labels: BE, 👀 테스트

#134 긴급! 타임아웃 에러
  backend/src/app.controller.ts
  backend/src/common/log/logger.ts
Labels: BE, 🚑 버그, 🚨 긴급

#148 이미지 리사이즈 기능 추가
  frontend/src/api/image/index.ts
  frontend/src/constants/api.ts
Labels: FE, 🌱 기능추가

#190 리드미에 시스템 아키텍처 사진 추가
  README.md
Labels: 📖 문서

#202 README에 로고 사진 추가 및 아키텍처 사진 수정
  README.md
Labels: 📖 문서

#205 배치 작업에서 DTO 일관되도록 수정
  backend/src/repl.ts
  backend/src/search/search.service.ts
Labels: BE, 🚑 버그, 🚨 긴급

#207 장소 검색 DTO에 맞게 수정
  backend/src/search/dto/PlaceSearchResponse.ts
  backend/src/search/search.service.ts
Labels: BE, 🚑 버그, 🚨 긴급
